Eagle.Web/ViewModels/ArticleViewModels.cs
using Eagle.Core.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Eagle.Web.ViewModels
{
    public class ArticleFormViewModel
    {
        public int Id { get; set; }
        [Display(Name = "عنوان مقاله")]
        [MaxLength(600, ErrorMessage = "{0} باید از 600 کارکتر کمتر باشد")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string Title { get; set; }

        [Display(Name = "توضیح")]
        [DataType(DataType.MultilineText)]
        [AllowHtml]
        public string Description { get; set; }
        public int ArticleCategoryId { get; set; }
        public HttpPostedFileBase ArticleImage { get; set; }

        public List<ArticleHeadLineViewModel> ArticleHeadLines { get; set; }
    }
    public class ArticleHeadLineViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        [DataType(DataType.MultilineText)]
        [AllowHtml]
        public string Description { get; set; }
    }

    public class ArticleInfoViewModel
    {
        public ArticleInfoViewModel()
        {
            
        }

        public ArticleInfoViewModel(Article article)
        {
            this.Id = article.Id;
            this.Title = article.Title;
            this.Author = article.User != null? $"{article.User.FirstName} {article.User.LastName}" : "-";
            this.ArticleCategory = article.ArticleCategory != null? article.ArticleCategory.Title : "-";
            this.PersianAddedDate = article.AddedDate != null? new PersianDateTime(article.AddedDate.Value).ToString() : "-";
        }
        public int Id { get; set; }
        [Display(Name = "عنوان")]
        public string Title { get; set; }
        [Display(Name = "نویسنده")]
        public string Author { get; set; }
        [Display(Name = "دسته بندی")]
        public string ArticleCategory { get; set; }
        [Display(Name = "تاریخ ثبت")]
        public string PersianAddedDate { get; set; }
    }
    public class CommentWithPersianDateViewModel : ArticleComment
    {
        public CommentWithPersianDateViewModel(ArticleComment comment)
        {
            this.Comment = comment;
            this.PersianDate = comment.AddedDate != null ? new PersianDateTime(comment.AddedDate.Value).ToString() : "-";
        }
        public ArticleComment Comment { get; set; }
        [Display(Name = "تاریخ ثبت")]
        public string PersianDate { get; set; }
    }
}

Eagle.Web/Areas/Admin/Controllers/ArticleCommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Eagle.Infrastructure.Repositories;
using Eagle.Core.Models;
using System.Net;
using Eagle.Web.ViewModels;

namespace Eagle.Web.Areas.Admin.Controllers
{
    [Authorize]
    public class ArticleCommentsController : Controller
    {
        private readonly ArticleCommentsRepository _repo;
        public ArticleCommentsController(ArticleCommentsRepository repo)
        {
            _repo = repo;
        }
        public ActionResult Index(int articleId)
        {
            ViewBag.ArticleName = _repo.GetArticleName(articleId);
            ViewBag.ArticleId = articleId;
            var comments = _repo.GetArticleComments(articleId);
            var commentsVm = new List<CommentWithPersianDateViewModel>();
            foreach (var comment in comments)
            {
                var commentVm = new CommentWithPersianDateViewModel(comment);
                commentsVm.Add(commentVm);
            }
            return View(commentsVm);
        }

        public ActionResult Create(int articleId)
        {
            ViewBag.ArticleId = articleId;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ArticleComment comment)
        {
            if (ModelState.IsValid)
            {
                comment.AddedDate = DateTime.Now;
                _repo.Add(comment);
                return RedirectToAction("Index", new { articleId = comment.ArticleId });
            }
            ViewBag.ArticleId = comment.ArticleId;
            return View(comment);
        }
        public ActionResult AnswerComment(int articleId,int parentCommentId)
        {
            ViewBag.ArticleId = articleId;
            ViewBag.ParentId = parentCommentId;
            return PartialView();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AnswerComment(ArticleComment comment)
        {
            var user = _repo.GetCurrentUser();
            comment.Name = user != null? $"{user.FirstName} {user.LastName}" : "ادمین";
            comment.Email = user != null ? user.Email :"-";
            comment.AddedDate = DateTime.Now;
            _repo.Add(comment);
            return RedirectToAction("Index", new { articleId = comment.ArticleId });
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticleComment comment = _repo.Get(id.Value);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ArticleComment comment)
        {
            if (ModelState.IsValid)
            {
                _repo.Update(comment);
                return RedirectToAction("Index", new { articleId = comment.ArticleId });
            }
            return View(comment);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticleComment comment = _repo.Get(id.Value);
            if (comment == null)
            {
                return HttpNotFound();
            }

            var commentVm = new CommentWithPersianDateViewModel(comment);
            return PartialView(commentVm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var articleId = _repo.Get(id).ArticleId;
            _repo.DeleteComment(id);
            return RedirectToAction("Index", new { articleId });
        }
    }
}

Eagle.Web/Areas/Admin/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Eagle.Core.Models;
using Eagle.Infrastructure;
using Eagle.Infrastructure.Helpers;
using Eagle.Infrastructure.Repositories;
using Eagle.Web.ViewModels;

namespace Eagle.Web.Areas.Admin.Controllers
{
    [Authorize]
    public class ArticlesController : Controller
    {
        private readonly ArticlesRepository _repo;
        public ArticlesController(ArticlesRepository repo)
        {
            _repo = repo;
        }
        // GET: Admin/Articles
        public ActionResult Index()
        {
            var articles = _repo.GetArticles();
            var articlesListVm = new List<ArticleInfoViewModel>();
            foreach (var article in articles)
            {
                var articleVm = new ArticleInfoViewModel(article);
                articlesListVm.Add(articleVm);
            }
            return View(articlesListVm);
        }
        // GET: Admin/Articles/Create
        public ActionResult Create()
        {
            ViewBag.ArticleCategoryId = new SelectList(_repo.GetArticleCategories(), "Id", "Title");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Article article, HttpPostedFileBase ArticleImage, string Tags)
        {
            if (ModelState.IsValid)
            {

                if (!HttpContext.User.Identity.IsAuthenticated)
                {
                    ViewBag.Message = "کاربر وارد کننده پیدا نشد.";
                    return View(article);
                }


                #region Upload Image
                if (ArticleImage != null)
                {
                    var newFileName = Guid.NewGuid() + Path.GetExtension(ArticleImage.FileName);
                    ArticleImage.SaveAs(Server.MapPath("/Files/ArticleImages/Image/" + newFileName));

                    ImageResizer thumb = new ImageResizer();
                    thumb.Resize(Server.MapPath("/Files/ArticleImages/Image/" + newFileName),
                        Server.MapPath("/Files/ArticleImages/Thumb/" + newFileName));

                    article.Image = newFileName;
                }
                #endregion

                _repo.AddArticle(article);

                if (!string.IsNullOrEmpty(Tags))
                    _repo.AddArticleTags(article.Id, Tags);

                return RedirectToAction("Index");
            }
            ViewBag.Tags = Tags;
            ViewBag.ArticleCategoryId = new SelectList(_repo.GetArticleCategories(), "Id", "Title", article.ArticleCategoryId);
            return View(article);
        }

        // GET: Admin/Articles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = _repo.GetArticle(id.Value);
            if (article == null)
            {
                return HttpNotFound();
            }
            ViewBag.Tags = _repo.GetArticleTagsStr(id.Value);
            ViewBag.ArticleCategoryId = new SelectList(_repo.GetArticleCategories(), "Id", "Title", article.ArticleCategoryId);
            return View(article);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Article article, HttpPostedFileBase ArticleImage, string Tags)
        {
            if (ModelState.IsValid)
            {
                #region Upload Image
                if (ArticleImage != null)
                {
                    if (System.IO.File.Exists(Server.MapPath("/Files/ArticleImages/Image/" + article.Image)))
                        System.IO.File.Delete(Server.MapPath("/Files/ArticleImages/Image/" + article.Image));

                    if (System.IO.File.Exists(Server.MapPath("/Files/ArticleImages/Thumb/" + article.Image)))
                        System.IO.File.Delete(Server.MapPath("/Files/ArticleImages/Thumb/" + article.Image));

                    var newFileName = Guid.NewGuid() + Path.GetExtension(ArticleImage.FileName);
                    ArticleImage.SaveAs(Server.MapPath("/Files/ArticleImages/Image/" + newFileName));

                    ImageResizer thumb = new ImageResizer();
                    thumb.Resize(Server.MapPath("/Files/ArticleImages/Image/" + newFileName), Server.MapPath("/Files/ArticleImages/Thumb/" + newFileName));
                    article.Image = newFileName;
                }
                #endregion

                _repo.Update(article);

                if (!string.IsNullOrEmpty(Tags))
                    _repo.AddArticleTags(article.Id, Tags);

                return RedirectToAction("Index");
            }
            ViewBag.Tags = Tags;
            ViewBag.ArticleCategoryId = new SelectList(_repo.GetArticleCategories(), "Id", "Title", article.ArticleCategoryId);
            return View(article);
        }

        [HttpPost]
        public ActionResult FileUpload()
        {
            var files = HttpContext.Request.Files;
            foreach (var fileName in files)
            {
                HttpPostedFileBase file = Request.Files[fileName.ToString()];
                var newFileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                file.SaveAs(Server.MapPath("/Files/ArticleImages/" + newFileName));
                TempData["UploadedFile"] = newFileName;
            }
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
        // GET: Admin/Articles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = _repo.GetArticle(id.Value);
            if (article == null)
            {
                return HttpNotFound();
            }
            return PartialView(article);
        }

        // POST: Admin/Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var article = _repo.Get(id);

            //#region Delete Article Image
            //if (article.Image != null)
            //{
            //    if (System.IO.File.Exists(Server.MapPath("/Files/ArticleImages/Image/" + article.Image)))
            //        System.IO.File.Delete(Server.MapPath("/Files/ArticleImages/Image/" + article.Image));

            //    if (System.IO.File.Exists(Server.MapPath("/Files/ArticleImages/Thumb/" + article.Image)))
            //        System.IO.File.Delete(Server.MapPath("/Files/ArticleImages/Thumb/" + article.Image));
            //}
            //#endregion

            _repo.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Eagle.Web/Areas/Admin/Views/Articles/Create.cshtml
@model Eagle.Core.Models.Article

@{
    ViewBag.Title = "مقاله ها";
}
<input type="hidden" id="nav_active" value="article_control">
<input type="hidden" id="nav_item_active" value="articles">
@{
    if (ViewBag.Message != null)
    {
        <div class="alert alert-danger">
            <strong>خطا!</strong> @ViewBag.Message
        </div>
    }
}
<div class="col-lg-12">
    <div class="card card-custom gutter-b">
        <div class="card-header">
            <h3 class="card-title">
                افزودن مقاله
            </h3>
        </div>
        @using (Html.BeginForm("Create", "Articles", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="card-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, new { })
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control " } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "form-text text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ArticleCategoryId, "دسته بندی", new { })
                    <div class="col-md-5">
                        @Html.DropDownList("ArticleCategoryId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ArticleCategoryId, "", new { @class = "form-text text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-label">تصویر</label>
                    <div class="col-lg-6 col-md-12 col-sm-12">
                        <div class="image-input image-input-outline" id="article-image">
                            <div class="image-input-wrapper" style="background-image: url(assets/media/users/100_1.jpg)"></div>

                            <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="change" data-toggle="tooltip" title="" data-original-title="آپلود تصویر">
                                <i class="fa fa-pen icon-sm text-muted"></i>
                                <input type="file" name="ArticleImage" accept=".png, .jpg, .jpeg" />
                                <input type="hidden" name="article_image_remove" />
                            </label>

                            <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="cancel" data-toggle="tooltip" title="حذف تصویر">
                                <i class="ki ki-bold-close icon-xs text-muted"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ShortDescription, new { })
                    @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control " } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "form-text text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Description, new { })
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control " } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "form-text text-danger" })
                </div>
                <div class="form-group">
                    <label for="ArticleTags">برچسب ها</label>
                    <input type="text" name="Tags" id="Tags" value="@ViewBag.Tags" placeholder="لطفا برچسب ها را با - از هم جدا کنید" class="form-control" />
                </div>
                @*<div id="headline-repeater" style="padding-top:50px">
                        <div class="form-group row" id="headline-repeater">
                            <label class="col-lg-2 col-form-label text-left">سر تیتر ها</label>
                            <div data-repeater-list="ArticleHeadLines" class="col-lg-10">
                                <div data-repeater-item class="form-group">
                                    <div class="form-group col-lg-4">
                                        <input class="form-control" type="text" name="Title" placeholder="عنوان">
                                    </div>
                                    <div class="col-md-4">
                                        <a href="javascript:;" data-repeater-delete="" class="btn btn-sm font-weight-bolder btn-light-danger">
                                            <i class="la la-trash-o"></i>حذف
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-lg-4">
                                <a href="javascript:;" data-repeater-create="" class="btn btn-sm font-weight-bolder btn-warning">
                                    <i class="la la-plus"></i>افزودن سر تیتر
                                </a>
                            </div>
                        </div>
                    </div>*@
            </div>
            <div class="card-footer">
                <a href="@Url.Action("Index")" class="btn btn-secondary">انصراف</a>
                <input type="submit" value="ثبت" class="btn btn-primary mr-2" />
            </div>
        }
    </div>
</div>
<style>
    .image-input .image-input-wrapper {
        width: 200px;
    }
</style>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="/ckeditor/ckeditor.js"></script>
    <script src="/ckeditor/adapters/jquery.js"></script>
    <script>
        $(function () {
            $('#Description').ckeditor();

        });
        $('#headline-repeater').repeater({
            initEmpty: true,
            show: function () {
                $(this).slideDown();
            },

            hide: function (deleteElement) {
                var currentInstance = $(this).index();
                var nextInstance = $(this).index() + 1;
                $(this).slideUp(deleteElement);
            }
        });
        new KTImageInput('article-image');
    </script>
}

Eagle.Web/Areas/Admin/Views/Articles/Edit.cshtml
@model Eagle.Core.Models.Article

@{
    ViewBag.Title = "مقاله ها";
}
<input type="hidden" id="nav_active" value="article_control">
<input type="hidden" id="nav_item_active" value="articles">
@{
    if (ViewBag.Message != null)
    {
        <div class="alert alert-danger">
            <strong>خطا!</strong> @ViewBag.Message
        </div>
    }
}
<div class="col-lg-12y">
    <div class="card card-custom gutter-b">
        <div class="card-header">
            <h3 class="card-title">
                ویرایش مقاله
            </h3>
        </div>
        @using (Html.BeginForm("Edit", "Articles", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.AddedDate)
            @Html.HiddenFor(model => model.UserId)
            @Html.HiddenFor(model => model.ViewCount)
            @Html.HiddenFor(model => model.Image)
            @Html.HiddenFor(model => model.InsertDate)
            @Html.HiddenFor(model => model.InsertUser)
            <div class="form-group">
                @Html.LabelFor(model => model.Title, new { })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control " } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "form-text text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ArticleCategoryId, "دسته بندی", new { })
                <div class="col-md-5">
                    @Html.DropDownList("ArticleCategoryId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ArticleCategoryId, "", new { @class = "form-text text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-label">تصویر</label>
                <div class="col-lg-6 col-md-12 col-sm-12">
                    <div class="image-input image-input-outline" id="article-image">
                        <div class="image-input-wrapper" style="background-image: url(/Files/ArticleImages/Thumb/@Model.Image)"></div>

                        <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="change" data-toggle="tooltip" title="" data-original-title="آپلود تصویر">
                            <i class="fa fa-pen icon-sm text-muted"></i>
                            <input type="file" name="ArticleImage" accept=".png, .jpg, .jpeg" />
                            <input type="hidden" name="article_image_remove" />
                        </label>

                        <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="cancel" data-toggle="tooltip" title="حذف تصویر">
                            <i class="ki ki-bold-close icon-xs text-muted"></i>
                        </span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ShortDescription, new { })
                @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "form-text text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Description, new { })
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "form-text text-danger" })
            </div>
            <div class="form-group">
                <label for="ArticleTags">برچسب ها</label>
                <input type="text" name="Tags" id="Tags" value="@ViewBag.Tags" placeholder="لطفا برچسب ها را با - از هم جدا کنید" class="form-control" />
            </div>
        </div>
            <div class="card-footer">
                <a href="@Url.Action("Index")" class="btn btn-secondary">انصراف</a>
                <input type="submit" value="ثبت" class="btn btn-primary mr-2" />
            </div>
        }
    </div>
</div>
<style>
    .image-input .image-input-wrapper {
        width: 200px;
    }
</style>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="/ckeditor/ckeditor.js"></script>
    <script src="/ckeditor/adapters/jquery.js"></script>
    <script>
        $(function () {
            $('#Description').ckeditor();

        });
        var avatar1 = new KTImageInput('article-image');
    </script>
}

Eagle.Web/Areas/Admin/Views/Articles/Index.cshtml
@model List<Eagle.Web.ViewModels.ArticleInfoViewModel>
@using Kendo.Mvc.UI
@using Eagle.Infrastructure.Helpers;
@{
    ViewBag.Title = "مقاله ها";
}
<input type="hidden" id="nav_active" value="article_control">
<input type="hidden" id="nav_item_active" value="articles">
<div class="card card-custom">
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
        <div class="card-title">
            <h3 class="card-label">
                @ViewBag.Title
                <span class="d-block text-muted pt-2 font-size-sm">ویرایش مقاله ها</span>
            </h3>
        </div>
        <div class="card-toolbar">
            <!--begin::Button-->
            <a href="/Admin/Articles/Create" class="btn btn-primary font-weight-bolder">
                <span class="svg-icon svg-icon-md">
                    <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg--><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <rect x="0" y="0" width="24" height="24" />
                            <circle fill="#000000" cx="9" cy="15" r="6" />
                            <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
                        </g>
                    </svg><!--end::Svg Icon-->
                </span>	رکورد جدید
            </a>
            <!--end::Button-->
        </div>
    </div>
    <div class="card-body">
        <!--begin: Datatable-->
        @(Html.Kendo().Grid(Model)
.Name("Grid")
.HtmlAttributes(new { style = "height:450px" })
.Columns(columns =>
{
columns.Bound(model => model.Title);
columns.Bound(model => model.Author);
columns.Bound(model => model.ArticleCategory);
columns.Bound(model => model.PersianAddedDate);
columns.Bound(item => @item.Id).IncludeInMenu(false).Sortable(false).Title("دستورات").Filterable(false).Groupable(false).Template(
        @<text>
            <a class='btn btn-sm btn-clean btn-icon mr-2' href="/Admin/Articles/Edit/@item.Id"><i class='far fa-edit text-primary'></i></a>
            <a class='btn btn-sm btn-clean btn-icon' onclick="@(CheckPermission.Check("articlesdelete") ? $"btnDelete({item.Id})" : "accessDenied()")"><i class='far fa-trash-alt text-danger'></i></a>
            @Html.ActionLink("سرتیتر ها", "Index", "ArticleHeadLines", new { articleId = @item.Id }, new { @class = "btn btn-primary btn-sm ml-2" })
            @Html.ActionLink("کامنت ها", "Index", "ArticleComments", new { articleId = @item.Id }, new { @class = "btn btn-primary btn-sm ml-2" })
        </text>
        ).Width(300);
})
    .Sortable()
    .Scrollable()
    .Pageable(pager => pager.PageSizes(new int[] { 10, 30, 50, 70, 100 }).Messages(m => m.ItemsPerPage("آیتم در هر صفحه").Display("")))
        .DataSource(dataSource => dataSource
        .Server()

        .Model(model => model.Id(item => item.Id))
    )
    .Filterable(filterable => filterable
        .Messages(m => m
            .Filter("فیلتر")
            .Clear("حذف")
            .Info("آن هایی را نشان بده که:")
            .And("و")
            .Or("یا")
            )
        .Operators(operators => operators
            .ForString(str => str.Clear()
                .IsEqualTo("برابر است با")
                .IsNotEqualTo("برابر نیست با")
                .Contains("شامل میشود")
                .DoesNotContain("شامل نمیشود")
                .StartsWith("شروع میشود با")
                .IsNullOrEmpty("خالی است")
                .IsNotNullOrEmpty("خالی نیست")
            )))
        )
        <!--end: Datatable-->
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="myModalHeader">
                <h5 class="modal-title" id="myModalLabel">Modal Title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i aria-hidden="true" class="ki ki-close"></i>
                </button>
            </div>
            <div class="modal-body" id="myModalBody">
                ...
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>

        $(document).ready(function () {
            $('.k-i-filter').removeClass("k-i-filter").addClass("k-icon k-i-more-vertical");
        });
    </script>
    <script>
        function btnDelete(id) {
            $.get("/Admin/Articles/Delete/" + id, function (result) {
                $("#myModal").modal();
                $("#myModalLabel").html("حذف مقاله");
                $("#myModalHeader");
                $("#myModalBody").html(result);
            });
        }
    </script>
}