Eagle.Web/Areas/Admin/Controllers/StaticContentDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Eagle.Core.Models;
using Eagle.Infrastructure;
using Eagle.Infrastructure.Helpers;
using Eagle.Infrastructure.Repositories;
using Eagle.Web.ViewModels;

namespace Eagle.Web.Areas.Admin.Controllers
{
    [Authorize]
    public class StaticContentDetailsController : Controller
    {
        private readonly StaticContentDetailsRepository _repo;
        public StaticContentDetailsController(StaticContentDetailsRepository repo)
        {
            _repo = repo;
        }
        // GET: Admin/StaticContentDetails
        public ActionResult Index()
        {
            return View(_repo.GetStaticContentDetails());
        }
        // GET: Admin/StaticContentDetails/Create
        public ActionResult Create()
        {
            ViewBag.StaticContentTypeId = new SelectList(_repo.GetStaticContentTypes(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StaticContentDetail staticContentDetail, HttpPostedFileBase StaticContentDetailImage)
        {
            if (ModelState.IsValid)
            {
                #region Upload Image
                if (StaticContentDetailImage != null)
                {
                    var newFileName = Guid.NewGuid() + Path.GetExtension(StaticContentDetailImage.FileName);
                    StaticContentDetailImage.SaveAs(Server.MapPath("/Files/StaticContentImages/Image/" + newFileName));

                    ImageResizer thumb = new ImageResizer();
                    thumb.Resize(Server.MapPath("/Files/StaticContentImages/Image/" + newFileName),
                        Server.MapPath("/Files/StaticContentImages/Thumb/" + newFileName));

                    staticContentDetail.Image = newFileName;
                }
                #endregion

                _repo.Add(staticContentDetail);

                return RedirectToAction("Index");
            }
            ViewBag.StaticContentTypeId = new SelectList(_repo.GetStaticContentTypes(), "Id", "Name", staticContentDetail.StaticContentTypeId);
            return View(staticContentDetail);
        }

        // GET: Admin/StaticContentDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StaticContentDetail staticContentDetail = _repo.GetStaticContentDetail(id.Value);
            if (staticContentDetail == null)
            {
                return HttpNotFound();
            }
            ViewBag.StaticContentTypeId = new SelectList(_repo.GetStaticContentTypes(), "Id", "Name", staticContentDetail.StaticContentTypeId);
            return View(staticContentDetail);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(StaticContentDetail staticContentDetail, HttpPostedFileBase StaticContentDetailImage)
        {
            if (ModelState.IsValid)
            {
                #region Upload Image
                if (StaticContentDetailImage != null)
                {
                    if (System.IO.File.Exists(Server.MapPath("/Files/StaticContentImages/Image/" + staticContentDetail.Image)))
                        System.IO.File.Delete(Server.MapPath("/Files/StaticContentImages/Image/" + staticContentDetail.Image));

                    if (System.IO.File.Exists(Server.MapPath("/Files/StaticContentImages/Thumb/" + staticContentDetail.Image)))
                        System.IO.File.Delete(Server.MapPath("/Files/StaticContentImages/Thumb/" + staticContentDetail.Image));

                    var newFileName = Guid.NewGuid() + Path.GetExtension(StaticContentDetailImage.FileName);
                    StaticContentDetailImage.SaveAs(Server.MapPath("/Files/StaticContentImages/Image/" + newFileName));

                    ImageResizer thumb = new ImageResizer();
                    thumb.Resize(Server.MapPath("/Files/StaticContentImages/Image/" + newFileName), Server.MapPath("/Files/StaticContentImages/Thumb/" + newFileName));
                    staticContentDetail.Image = newFileName;
                }
                #endregion

                _repo.Update(staticContentDetail);
                return RedirectToAction("Index");
            }
            ViewBag.StaticContentTypeId = new SelectList(_repo.GetStaticContentTypes(), "Id", "Name", staticContentDetail.StaticContentTypeId);
            return View(staticContentDetail);
        }
        // GET: Admin/StaticContentDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StaticContentDetail staticContentDetail = _repo.GetStaticContentDetail(id.Value);
            if (staticContentDetail == null)
            {
                return HttpNotFound();
            }
            return PartialView(staticContentDetail);
        }

        // POST: Admin/StaticContentDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var staticContentDetail = _repo.Get(id);

            //#region Delete StaticContentDetail Image
            //if (staticContentDetail.Image != null)
            //{
            //    if (System.IO.File.Exists(Server.MapPath("/Files/StaticContentImages/Image/" + staticContentDetail.Image)))
            //        System.IO.File.Delete(Server.MapPath("/Files/StaticContentImages/Image/" + staticContentDetail.Image));

            //    if (System.IO.File.Exists(Server.MapPath("/Files/StaticContentImages/Thumb/" + staticContentDetail.Image)))
            //        System.IO.File.Delete(Server.MapPath("/Files/StaticContentImages/Thumb/" + staticContentDetail.Image));
            //}
            //#endregion

            _repo.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Eagle.Web/Areas/Admin/Views/StaticContentDetails/Create.cshtml
@model Eagle.Core.Models.StaticContentDetail

@{
    ViewBag.Title = "جزئیات محتوا";
}
<input type="hidden" id="nav_active" value="static_content">
<input type="hidden" id="nav_item_active" value="content">
@{
    if (ViewBag.Message != null)
    {
        <div class="alert alert-danger">
            <strong>خطا!</strong> @ViewBag.Message
        </div>
    }
}
<div class="col-lg-12">
    <div class="card card-custom gutter-b">
        <div class="card-header">
            <h3 class="card-title">
                افزودن محتوا
            </h3>
        </div>
        @using (Html.BeginForm("Create", "StaticContentDetails", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.StaticContentTypeId, "نوع محتوا", new { })
                <div class="col-md-5">
                    @Html.DropDownList("StaticContentTypeId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.StaticContentTypeId, "", new { @class = "form-text text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Title, new { })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control " } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "form-text text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-label">تصویر</label>
                <div class="col-lg-6 col-md-12 col-sm-12">
                    <div class="image-input image-input-outline" id="static-content-image">
                        <div class="image-input-wrapper" style="background-image: url(assets/media/users/100_1.jpg)"></div>

                        <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="change" data-toggle="tooltip" title="" data-original-title="آپلود تصویر">
                            <i class="fa fa-pen icon-sm text-muted"></i>
                            <input type="file" name="StaticContentDetailImage" accept=".png, .jpg, .jpeg" />
                            <input type="hidden" name="static-content_image_remove" />
                        </label>

                        <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="cancel" data-toggle="tooltip" title="حذف تصویر">
                            <i class="ki ki-bold-close icon-xs text-muted"></i>
                        </span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ShortDescription, new { })
                @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "form-text text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Description, new { })
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "form-text text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Link, new { })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control " } })
                    @Html.ValidationMessageFor(model => model.Link, "", new { @class = "form-text text-danger" })
                </div>
            </div>
        </div>
            <div class="card-footer">
                <a href="@Url.Action("Index")" class="btn btn-secondary">انصراف</a>
                <input type="submit" value="ثبت" class="btn btn-primary mr-2" />
            </div>
        }
    </div>
</div>
<style>
    .image-input .image-input-wrapper {
        width: 200px;
    }
</style>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="/ckeditor/ckeditor.js"></script>
    <script src="/ckeditor/adapters/jquery.js"></script>
    <script>
        $(function () {
            $('#Description').ckeditor();

        });
        new KTImageInput('static-content-image');
    </script>
}

Eagle.Web/Areas/Admin/Views/StaticContentDetails/Delete.cshtml
@model Eagle.Core.Models.StaticContentDetail

@{
    ViewBag.Title = "Delete";
}
<h4 class="card-label">
    آیا مطمئن هستید که می خواهید این آیتم را حذف کنید؟
</h4>
<dl class="row" style="padding-top: 10px">
    <dt class="col-sm-4">
        @Html.DisplayNameFor(model => model.StaticContentType.Name)
    </dt>
    <dd class="col-sm-8">
        @Html.DisplayFor(model => model.StaticContentType.Name)
    </dd>
    <dt class="col-sm-4">
        @Html.DisplayNameFor(model => model.Title)
    </dt>
    <dd class="col-sm-8">
        @Html.DisplayFor(model => model.Title)
    </dd>
    <dt class="col-sm-4">
        @Html.DisplayNameFor(model => model.ShortDescription)
    </dt>
    <dd class="col-sm-8">
        @Html.DisplayFor(model => model.ShortDescription)
    </dd>
</dl>
<div style="float:left">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <input type="submit" value="حذف" class="btn btn-danger mr-2" />
    }
</div>

Eagle.Web/Areas/Admin/Views/StaticContentDetails/Edit.cshtml
@model Eagle.Core.Models.StaticContentDetail

@{
    ViewBag.Title = "جزئیات محتوا";
}
<input type="hidden" id="nav_active" value="static_content">
<input type="hidden" id="nav_item_active" value="content">
@{
    if (ViewBag.Message != null)
    {
        <div class="alert alert-danger">
            <strong>خطا!</strong> @ViewBag.Message
        </div>
    }
}
<div class="col-lg-12">
    <div class="card card-custom gutter-b">
        <div class="card-header">
            <h3 class="card-title">
                ویرایش محتوا
            </h3>
        </div>
        @using (Html.BeginForm("Edit", "StaticContentDetails", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.Image)
            @Html.HiddenFor(model => model.InsertDate)
            @Html.HiddenFor(model => model.InsertUser)
            <div class="form-group">
                @Html.LabelFor(model => model.StaticContentTypeId, "نوع محتوا", new { })
                <div class="col-md-5">
                    @Html.DropDownList("StaticContentTypeId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.StaticContentTypeId, "", new { @class = "form-text text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Title, new { })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control " } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "form-text text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-label">تصویر</label>
                <div class="col-lg-6 col-md-12 col-sm-12">
                    <div class="image-input image-input-outline" id="static-content-image">
                        <div class="image-input-wrapper" style="background-image: url(/Files/StaticContentImages/Thumb/@Model.Image)"></div>

                        <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="change" data-toggle="tooltip" title="" data-original-title="آپلود تصویر">
                            <i class="fa fa-pen icon-sm text-muted"></i>
                            <input type="file" name="StaticContentDetailImage" accept=".png, .jpg, .jpeg" />
                            <input type="hidden" name="static-content_image_remove" />
                        </label>

                        <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="cancel" data-toggle="tooltip" title="حذف تصویر">
                            <i class="ki ki-bold-close icon-xs text-muted"></i>
                        </span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ShortDescription, new { })
                @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "form-text text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Description, new { })
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "form-text text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Link, new { })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control " } })
                    @Html.ValidationMessageFor(model => model.Link, "", new { @class = "form-text text-danger" })
                </div>
            </div>
        </div>
            <div class="card-footer">
                <a href="@Url.Action("Index")" class="btn btn-secondary">انصراف</a>
                <input type="submit" value="ثبت" class="btn btn-primary mr-2" />
            </div>
        }
    </div>
</div>
<style>
    .image-input .image-input-wrapper {
        width: 200px;
    }
</style>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="/ckeditor/ckeditor.js"></script>
    <script src="/ckeditor/adapters/jquery.js"></script>
    <script>
        $(function () {
            $('#Description').ckeditor();

        });
        new KTImageInput('static-content-image');
    </script>
}

Eagle.Web/Areas/Admin/Views/StaticContentDetails/Index.cshtml
@model List<Eagle.Core.Models.StaticContentDetail>
@using Kendo.Mvc.UI
@using Eagle.Infrastructure.Helpers;
@{
    ViewBag.Title = "جزئیات محتوا";
}
<input type="hidden" id="nav_active" value="static_content">
<input type="hidden" id="nav_item_active" value="content">
<div class="card card-custom">
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
        <div class="card-title">
            <h3 class="card-label">
                @ViewBag.Title
                <span class="d-block text-muted pt-2 font-size-sm">ویرایش محتوا </span>
            </h3>
        </div>
        <div class="card-toolbar">
            <!--begin::Button-->
            <a href="/Admin/StaticContentDetails/Create" class="btn btn-primary font-weight-bolder">
                <span class="svg-icon svg-icon-md">
                   <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <rect x="0" y="0" width="24" height="24" />
                            <circle fill="#000000" cx="9" cy="15" r="6" />
                            <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
                        </g>
                    </svg>
                </span>	رکورد جدید
            </a>
            <!--end::Button-->
        </div>
    </div>
    <div class="card-body">
        <!--begin: Datatable-->
        @(Html.Kendo().Grid(Model)
        .Name("Grid")
        .HtmlAttributes(new { style = "height:450px" })
        .Columns(columns =>
        {
            columns.Bound(model => model.Title);
            columns.Bound(model => model.ShortDescription);
            columns.Bound(item => @item.Id).IncludeInMenu(false).Sortable(false).Title("دستورات").Filterable(false).Groupable(false).Template(
                @<text>
                    <a class='btn btn-sm btn-clean btn-icon mr-2' href="/Admin/StaticContentDetails/Edit/@item.Id"><i class='far fa-edit text-primary'></i></a>
                    <a class='btn btn-sm btn-clean btn-icon' onclick="@(CheckPermission.Check("staticcontentdetailsdelete") ? $"btnDelete({item.Id})" : "accessDenied()")"><i class='far fa-trash-alt text-danger'></i></a>
                </text>
                ).Width(300);
            })
                .Sortable()
                .Scrollable()
                .Pageable(pager => pager.PageSizes(new int[] { 10, 30, 50, 70, 100 }).Messages(m => m.ItemsPerPage("آیتم در هر صفحه").Display("")))
                    .DataSource(dataSource => dataSource
                    .Server()

                    .Model(model => model.Id(item => item.Id))
                )
                .Filterable(filterable => filterable
                    .Messages(m => m
                        .Filter("فیلتر")
                        .Clear("حذف")
                        .Info("آن هایی را نشان بده که:")
                        .And("و")
                        .Or("یا")
                        )
                    .Operators(operators => operators
                        .ForString(str => str.Clear()
                            .IsEqualTo("برابر است با")
                            .IsNotEqualTo("برابر نیست با")
                            .Contains("شامل میشود")
                            .DoesNotContain("شامل نمیشود")
                            .StartsWith("شروع میشود با")
                            .IsNullOrEmpty("خالی است")
                            .IsNotNullOrEmpty("خالی نیست")
                        )))
        )
        <!--end: Datatable-->
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="myModalHeader">
                <h5 class="modal-title" id="myModalLabel">Modal Title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i aria-hidden="true" class="ki ki-close"></i>
                </button>
            </div>
            <div class="modal-body" id="myModalBody">
                ...
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>

        $(document).ready(function () {
            $('.k-i-filter').removeClass("k-i-filter").addClass("k-icon k-i-more-vertical");
        });
    </script>
    <script>
        function btnDelete(id) {
            $.get("/Admin/StaticContentDetails/Delete/" + id, function (result) {
                $("#myModal").modal();
                $("#myModalLabel").html("حذف محتوا");
                $("#myModalHeader");
                $("#myModalBody").html(result);
            });
        }
    </script>
}